image: node

stages:
  - yarn
  - test
  - build
  - release

yarn:
  stage: yarn
  script:
    - yarn install
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - yarn
  script:
    - yarn lint
    - yarn prettier-check
    - yarn test

build:
  stage: build
  before_script:
    - echo $CI_JOB_ID
    - echo BUILD_JOB_ID=$CI_JOB_ID >> build.env
  script:
    - yarn build
  artifacts:
    paths:
      - "dist/va-embeddable-chat.css"
      - "dist/va-embeddable-chat.js"
    reports:
      # export the environment statement, so we can access it in the release stage.
      dotenv: build.env

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build
      artifacts: true
  script:
    - echo Releasing artifacts created in Job $GE_JOB_ID
  release:
    name: 'Release artifact from $CI_COMMIT_SHORT_SHA'
    description: 'Created using the release-cli'
    tag_name: '$CI_COMMIT_SHORT_SHA'
    assets:
      links:
        - name: 'JavaScript'
          url: '${CI_PROJECT_URL}/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/va-embeddable-chat.js'
        - name: 'CSS'
          url: '${CI_PROJECT_URL}/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/va-embeddable-chat.css'
  only:
    - D8TSDT-518-library-mode
