image: node:21.5.0

stages:
  - pnpm
  - test
  - build
  - release

pnpm:
  stage: pnpm
  before_script:
    - npm install -g pnpm
    - node -v
    - pnpm -v
  script:
    - pnpm install
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - pnpm
  before_script:
    - npm install -g pnpm
  script:
    - pnpm run lint
    - pnpm run prettier-check
    - pnpm run test

build:
  stage: build
  dependencies:
    - test
    - pnpm
  before_script:
    - echo $CI_JOB_ID
    - echo BUILD_JOB_ID=$CI_JOB_ID >> build.env
    - npm install -g pnpm
  script:
    - pnpm run build
  artifacts:
    paths:
      - "dist/virtual-assistant-chat.css"
      - "dist/virtual-assistant-chat.js"
    reports:
      # export the environment statement, so we can access it in the release stage.
      dotenv: build.env

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build
      artifacts: true
  script:
    - echo Releasing artifacts created in Job $BUILD_JOB_ID
  release:
    name: 'Release $CI_COMMIT_TAG - Job ID $BUILD_JOB_ID'
    description: 'Embeddable Virtual Assistant chat.'
    tag_name: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'JavaScript'
          url: '${CI_PROJECT_URL}/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/virtual-assistant-chat.js'
        - name: 'CSS'
          url: '${CI_PROJECT_URL}/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/virtual-assistant-chat.css'
  only:
    - tags
