services:
  jwt:
    image: node:lts
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8088:8088"
    environment:
      - JWT_SECRET=${JWT_SECRET:-123}
    command: bash -c "node ./tests/jwt-issuer.js"
  backend:
    image: node:lts
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5001:5001"
    command: bash -c "node ./tests/backend.js"
