import { Documents } from "../components/Documents.jsx";

export default {
  title: "Chat/Documents",
  component: Documents,
};

export const Default = {
  args: {
    documents: [
      {
        language: "EN",
        title:
          "Speech by Commissioner McGuinness on 'Financing the transition – Green and Digital' at the Global Economic Summit",
        source: "Press Corner",
        source_url:
          "https://ec.europa.eu/commission/presscorner/detail/en/SPEECH_24_2805",
        source_ref: 201501,
        source_date: "2024-05-23T16:00:43+02:00",
        extra: {
          content_type: "text",
          result_id: "1d41194f-42f2-4ec0-8a6d-caccfc1732b5",
          file_id: "fa42b922-781d-4f29-849e-738026b69455",
          file_name: "PressCorner-SPEECH-201501.txt",
          meta_file_name: "PressCorner-SPEECH-201501.txt",
          page: 1,
          commissionerCodes: ["MCGUINNES"],
          docuType: "SPEECH",
          eventDate: "2024-05-20",
          extra_id: 651961,
          original: true,
          placeKy: 49039,
          policyCodes: ["FINSTAB", "PR-GREENDEAL", "PR-DIGITAL"],
          refCode: "SPEECH/24/2805",
          subTitle: "Financing the transition – Green and Digital",
        },
        pending_review: null,
        assignee: null,
        id: "9173a0920ffc9640d2e1a4e69af0afaa",
        content:
          "And I think the issues that are top of mind for citizens and indeed businesses are migration, cost of living, environment, shortage of workers, housing and infrastructure.\nAnd these debates are everywhere. They're heated and they're becoming increasingly very divisive.\nSo if I look back to when the European Commission launched the Green Deal in December 2019, it really did herald a very ambitious plan to make the EU economy climate neutral by 2050.\nAnd the Green Deal was for everybody, you know, from energy to housing to farming.\nAnd the push for action to address this problem of climate and environmental degradation was really strong, including from environmental groups and civil society.\nAnd I think it still is today.\nBut there is a but here.\nI think there is a change, certainly in the last year, and there's still huge awareness of the challenges that we all face and the things we need to do.\nBut there is a little pushback, about how we do it, the time frame for action and how the transition will be financed.\nI was fascinated about two thirds that know what we need to do and the one third that are different.\nBut I also have a suspicion that the two thirds who know what needs to be done, sometimes when it comes to actually doing it, also find themselves a little bit hesitant.\n",
        score: 0.81494140625,
        rating: "A",
        keywords: null,
      },
      {
        language: "EN",
        title:
          "Commission welcomes completion of key ‘Fit for 55' legislation, putting EU on track to exceed 2030 targets",
        source: "Press Corner",
        source_url:
          "https://ec.europa.eu/commission/presscorner/detail/en/IP_23_4754",
        source_ref: 197201,
        source_date: "2023-10-09T12:09:10+02:00",
        extra: {
          content_type: "text",
          result_id: "5a7da532-8d05-4533-9272-ca11fc9e9e90",
          file_id: "d8b07bb1-7f06-44d0-862b-cc7b74a4bf87",
          file_name: "PressCorner-IP-197201.txt",
          meta_file_name: "PressCorner-IP-197201.txt",
          page: 1,
          commissionerCodes: [
            "UVONDERLEYEN",
            "KADRISIMSO",
            "ADINAVĂLEA",
            "SEFCOVIC",
          ],
          docuType: "IP",
          dolaAvResources: [
            {
              date: "2023-10-08T22:00:00.000+00:00",
              reference: null,
              image: {
                fileName: "fit-for-55.jpg",
                copyright: "European Union 2023",
                size: 103339,
                author: "NA",
                description: "Fit fo 55",
                id: 1801,
                content: null,
                inputDate: "2023-10-08T22:00:00.000+00:00",
              },
              year: "2023",
              thumb:
                "https://ec.europa.eu/commission/presscorner/api/image/content/fit-for-55.jpg",
              isNMS: true,
              dolaAVType: "PHOTO",
              title: "Fit fo 55",
              ky: 114011,
              url: "https://ec.europa.eu/commission/presscorner/api/image/content/fit-for-55.jpg",
            },
          ],
          eventDate: "2023-10-09",
          extra_id: 635433,
          leadText:
            "The Commission welcomes today's adoption of two final pillars of its ‘Fit for 55' legislative package for delivering the EU's 2030 climate targets.",
          original: true,
          placeKy: 1,
          policyCodes: ["CLIMACTION", "ENERGY", "TRANSPORT", "PR-GREENDEAL"],
          refCode: "IP/23/4754",
          subTitle: "Completion of key ‘Fit for 55' legislation",
        },
        pending_review: null,
        assignee: null,
        id: "d0f4aab170a9aaa808a911b2e64ea01c",
        content:
          "The FuelEU Maritime Regulation will promote the uptake of renewable and low-carbon fuels through the establishment of a target for gradual reductions for the annual average GHG intensity of the energy used onboard by ships.\nNext steps\nThe implementation of the 'Fit for 55' legislation is now starting in the Member States. The National Energy and Climate Plans (NECPs) currently being finalised by Member States will need to integrate this new legislation and demonstrate how the 2030 climate and energy targets will be met at national level.\nAs announced by President von der Leyen in her annual State of the European Union speech, the Commission will be engaging in a series of dialogues with citizens and industry on the implementation of the European Green Deal legislation, under the guidance of Executive Vice-President Maros Šefčovič. In addition to climate legislation, development and implementation continues of the other, complementary, pillars of the European Green Deal. The European Parliament and the Council are currently negotiating several energy, circular economy, pollution and nature-related laws, with the Commission providing intensive support to make sure all these are agreed in the coming months.\nBackground\nThe European Green Deal, presented by the Commission on 11 December 2019, set out a new growth strategy for Europe. It aims to transform the EU into a fair and prosperous society, with a modern, resource-efficient and competitive economy with zero net greenhouse gas emissions by 2050 and with economic growth decoupled from resource use.\n",
        score: 0.50830078125,
        rating: "C",
        keywords: null,
      },
      {
        language: "EN",
        title:
          "State aid: Commission approves €6.5 billion German scheme to address carbon leakage risk for energy-intensive companies resulting from national fuel emission trading system",
        source: "Press Corner",
        source_url:
          "https://ec.europa.eu/commission/presscorner/detail/en/IP_23_4105",
        source_ref: 196523,
        source_date: "2023-08-10T11:45:17+02:00",
        extra: {
          content_type: "text",
          result_id: "a5968a87-3556-41d6-b033-41bb02732d0b",
          file_id: "330600c5-dd6e-4008-9449-a14a3c69e29d",
          file_name: "PressCorner-IP-196523.txt",
          meta_file_name: "PressCorner-IP-196523.txt",
          page: 1,
          commissionerCodes: ["VESTAGER"],
          docuType: "IP",
          eventDate: "2023-08-10",
          extra_id: 633056,
          leadText:
            "The European Commission has approved, under EU State aid rules, a €6.5 billion German scheme to partially compensate energy-intensive companies to address the risk of carbon leakage from higher fuel prices resulting from the German fuel emission trading system (‘German fuel ETS').",
          original: true,
          placeKy: 1,
          policyCodes: ["COMPETY", "STATAID"],
          refCode: "IP/23/4105",
          subTitle: "State aid: Commission approves €6.5 billion German scheme",
        },
        pending_review: null,
        assignee: null,
        id: "75295318cf41cc76a7f9358eea83441b",
        content:
          "Moreover, the Commission considers that by making the aid conditional upon energy efficiency and decarbonisation efforts, the measure contributes to the objective of maximising the incentives for a cost-effective decarbonisation of the economy. It therefore supports the EU's climate and environmental objectives and the goals set in the European Green Deal. Furthermore, the Commission concluded that the aid granted is limited to the minimum necessary and will not have undue negative effects on competition and trade in the EU.\nOn this basis, the Commission approved the German scheme under EU State aid rules.\nBackground\nThe European Green Deal, presented by the Commission on 11 December 2019, sets the goal of making Europe the first climate-neutral continent by 2050. The EU ETS is a cornerstone of the EU's policy to combat climate change and a key tool for curbing greenhouse gas emissions cost-effectively. On 30 June 2021, the European Parliament and the Council adopted the European Climate Law endorsing the binding target to cut emissions by at least 55% by 2030, compared to 1990 levels.\nOn 10 May 2023, the European Parliament and the Council adopted the revised EU ETS Directive which introduced an emissions trading system for buildings, road transport and additional sectors not covered by the current ETS. The ETS2 will be a separate, but complementary, trading system and the auctioning of allowances under it will start in 2027.\n",
        score: 0.28515625,
        rating: "D",
        keywords: null,
      },
      {
        language: "EN",
        title:
          "Keynote speech by Executive Vice-President Šefčovič on the European Green Deal at the European Conference of Harvard University ",
        source: "Press Corner",
        source_url:
          "https://ec.europa.eu/commission/presscorner/detail/en/SPEECH_24_741",
        source_ref: 199879,
        source_date: "2024-02-11T17:20:41+01:00",
        extra: {
          content_type: "text",
          result_id: "865d87d5-7b84-47c8-8676-36c00fc3cc5d",
          file_id: "4c2fac23-9f3d-4204-a93c-0ac1e1b60c7b",
          file_name: "PressCorner-SPEECH-199879.txt",
          meta_file_name: "PressCorner-SPEECH-199879.txt",
          page: 1,
          commissionerCodes: ["SEFCOVIC"],
          docuType: "SPEECH",
          eventDate: "2024-02-10",
          extra_id: 645488,
          original: true,
          placeKy: 4215,
          policyCodes: ["CLIMACTION", "ENERGY"],
          refCode: "SPEECH/24/741",
          subTitle: "Speech by EVP Šefčovič at Harvard University Conference",
        },
        pending_review: null,
        assignee: null,
        id: "36d44441431070e7f0f558c5245390e5",
        content:
          "A little over four years ago, we launched what we called the European Green Deal, an overarching, umbrella plan to help us manage this transition in Europe – more precisely, to become the first climate neutral continent by 2050, while growing our economy.\nOver the first phase of the Green Deal, we have steadily put in place the credible targets and regulations necessary to bring about the required change.\nWe have unleashed the largest funding scheme in our history, to mobilise at least 1 trillion euros in sustainable investments over the next few years.\nOur focus has now shifted to action. Turning the measures we have agreed upon into reality.\nThe challenge is monumental. And we need everybody on board.\nNow, we will apply a new working relationship with industry – so that its transformation and competitiveness go hand in hand.\nWe work on a new consensus on the future of agriculture – so that it is sustainable and generates decent incomes for its workers.\nAnd social acceptance – by making green solutions accessible to everyone, and by creating quality jobs at all skill levels.\n\nSo, what will Europe's journey look like in the coming years?\nFirst, many of you will be familiar with the EU's Single Market. This is perhaps the biggest asset we have, our greatest tool for investment, and a catalyst for economic growth for more than 30 years.\n",
        score: 0.056976318359375,
        rating: "E",
        keywords: null,
      },
      {
        language: "EN",
        title: "Daily News 09 / 10 / 2023",
        source: "Press Corner",
        source_url:
          "https://ec.europa.eu/commission/presscorner/detail/en/MEX_23_4842",
        source_ref: 197280,
        source_date: "2023-10-09T12:37:03+02:00",
        extra: {
          content_type: "text",
          result_id: "014ec4cb-3fc7-464d-a4a2-54aa5493494f",
          file_id: "a36fff86-0a95-4e22-bb0b-d13fd352c810",
          file_name: "PressCorner-MEX-197280-0.txt",
          meta_file_name: "PressCorner-MEX-197280-0.txt",
          page: 1,
          docuType: "MEX",
          eventDate: "2023-10-09",
          extra_id: 635831,
          original: true,
          placeKy: 1,
          policyCodes: ["GENINFO"],
          refCode: "MEX/23/4842",
          subTitle: "Daily News 09 / 10 / 2023",
        },
        pending_review: null,
        assignee: null,
        id: "64b5d697432f40f712281d4541a516cb",
        content:
          "While this legislative package is a central part of the European Green Deal, work continues on other pending legislative files and proposals, and implementation is now starting in the Member States.\nA press release and Q&As on the Emission Trading System and Social Climate Fund, Effort sharing and natural carbon sinks, Making our energy system Fit for 55, Sustainable Transport, and Carbon Border Adjustment Mechanism are available online.\n(For more information: Tim McPhie – Tel.: +32 2 295 86 02; Adalbert Jahnz – Tel.: +32 2 295 31 56; Daniel Ferrie – Tel.: +32 2 298 65 00)",
        score: 0.0017337799072265625,
        rating: "E",
        keywords: null,
      },
    ],
  },
};
