name: Release

on:
  push:
    tags:
      - '*'

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.7.1

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Cache pnpm store and cypress binary
        with:
          path: |
            ${{ env.STORE_PATH }}
            ~/.cache/Cypress
          key: ${{ runner.os }}-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload CSS
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/virtual-assistant-chat.css
          asset_name: virtual-assistant-chat-${{ github.ref_name }}.css
          asset_content_type: text/css
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JS
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/virtual-assistant-chat.js
          asset_name: virtual-assistant-chat-${{ github.ref_name }}.js
          asset_content_type: application/javascript
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
